"""Initial migration

Revision ID: 894358647edc
Revises:
Create Date: 2026-07-18 23:02:38.747600

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "894358647edc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
